name: Java CI with Maven

on:
  push:
    branches: [ "main" ]     # chạy khi push lên nhánh main
  pull_request:
    branches: [ "main" ]     # chạy khi có pull request vào main

jobs:
  build:
    runs-on: ubuntu-latest   # chạy trên máy ảo Ubuntu

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run tests
        run: mvn test
